# configs
run-shell "#{d:config_files}/configs/bind-key.tmux"
run-shell "#{d:config_files}/configs/options.tmux"

# theme
run-shell "#{d:config_files}/themes/onedark.tmux"

# plugins
run-shell "#{d:config_files}/plugins/tmux-sensible/sensible.tmux"
run-shell "#{d:config_files}/plugins/tmux-yank/yank.tmux"
run-shell "#{d:config_files}/plugins/tmux-urlview/urlview.tmux"
run-shell "#{d:config_files}/plugins/tmux-cpu/cpu.tmux"
run-shell "#{d:config_files}/plugins/tmux-battery/battery.tmux"
run-shell "#{d:config_files}/plugins/tmux-prefix-highlight/prefix_highlight.tmux"
run-shell "#{d:config_files}/plugins/tmux-online-status/online_status.tmux"
run-shell "#{d:config_files}/plugins/tmux-better-mouse-mode/scroll_copy_mode.tmux"
